### ISSUE TITLE
Remove fc/string.hpp to_string impls

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1057]
Verify `fc/string.hpp` functionality is not used in consensus and change to use `std::to_string` where possible.

**Comment by greg7mdp** [comment]
`fc::to_string` provides the same output as `std::to_string` for integer types, so it can be removed for these types.

However, the version for `double` does not matche the `std::to_string` output. See below:

```
Test values: 23.43, 1e-9, 1e40, 1e-40, 123456789.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::infinity()
=====================================================================================================================================

fc::to_string:  23.42999999999999972
std::to_string: 23.430000

fc::to_string:  0.00000000100000000
std::to_string: 0.000000

fc::to_string:  10000000000000000303786028427003666890752.00000000000000000
std::to_string: 10000000000000000303786028427003666890752.000000

fc::to_string:  0.00000000000000000
std::to_string: 0.000000

fc::to_string:  123456789.00000000000000000
std::to_string: 123456789.000000

fc::to_string:  nan
std::to_string: nan

fc::to_string:  inf
std::to_string: inf
```

After replacing the uses of `fc::to_string` for integer types with `std::to_string`, we are left with a single occurence of usage of `std::string to_string(double);` in variant.cpp. Since I am worried about this causing a consensus change, I kept the old implementation as a static function in `variant.cpp`, and I removed all `to_string()` overloads from the fc `string.hpp` header.
