### ISSUE TITLE
leap-util is unable to successfully run a detailed smoke test and trim the blocklog.

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/leap#1348]
Investigate errors in `leap-util` smoke test and trim.

**Comment by dimas1185** [comment]
@Rossco99 What do you think the issue is? As per what I see it looks like an error is somewhere else since you have a wrong index file reported. `smoke-test` performs its task and informs you about that. So error description doesn't make sense or you believe it is wrong and your index is alright?

regarding the trimming, it looks like `eosio-blocklog` ignores index mismatch. I think `leap-util` does here better job informing you that you have a different index file. Let me know what do you think issue is and what is expected behavior.

**Comment by eosusa** [comment]
Copying from the Node Operators TG chat:

as weve discussed, heres my standard process i have to run every few weeks after some nodes crash.  blocklog is corrupted due to server crash, snapshot cant repair.  have to trim last few 100 blocks with eosio-blocklog and then snap launches properly and proceeds syncing.  seems like the snap process could handle that trimming back (to before lib i think) instead of the cryptic error and unknown voodoo of trimming the log manually.
![image](https://github.com/AntelopeIO/leap/assets/47283932/9c82a592-0864-4832-ac46-f4b5c8649d67)
![image](https://github.com/AntelopeIO/leap/assets/47283932/44b41514-1015-4b63-92bc-1ce41f9d5f04)
![image](https://github.com/AntelopeIO/leap/assets/47283932/a74ee6b1-f73d-4679-9bec-edf9caf5b79e)

as u can see, i need to know the last block number thats in the blocklog to know where to trim it to.  the new leap-util doesnt give me the same start/end block numbers like the original eosio-blocklog did.  which makes this recovery process even THAT much more difficult
![image](https://github.com/AntelopeIO/leap/assets/47283932/77f8e834-61b7-4fcd-b95b-1bb46f092b75)

**Comment by dimas1185** [comment]
issue:
we validate blocks log bundle before printing actual first/last block numbers and throw exception with only a range difference between first and last block. This over-complicates node crash recovery as people need more information to do this smoothly.
possible fix:
move validation part out of constructor of `block_log_bundle` class and execute it later in `block_log::smoke_test`.
