### ISSUE TITLE
IF : Extra padding is added to the hs_bitset when constructing a quorum_certificate from a quorum_certificate_message 

### ISSUE THREAD

**Issue by systemzax** [AntelopeIO/leap#1626]
Printing a quorum_certificate bitset when created :
Id : PVT_BLS_r4ZpChd87ooyzl6MIkw23k7PRX8xptp7TczLJHCIIW88h/hS finalizers 21 000000111111111111111

Printing a quorum_certificate bitset when received :
Id : PVT_BLS_/l7xzXANaB+GrlTsbZEuTiSOiWTtpBoog+TZnirxUUSaAfCo finalizers 32 00000000000000000111111111111111

The message format seems to (correctly) encode the bitset using the minimum required number of unsigned integers to represent the active finalizer set votes, but the decoding should also trim the extra leading zeroes.

**Comment by greg7mdp** [comment]
I think the leading zeroes are meaningful, as the first output is exactly 21 binary digits and the second exactly 32, so in my opinion they should not be trimmed.

**Comment by heifner** [comment]
> If I understand correctly, and the first bitset is for 21 finalizers and the second for 32 finalizers, I think the leading zeroes are meaningful, as the first output is exactly 21 binary digits and the second exactly 32, so in my opinion they should not be trimmed.

The issue is that the conversion to "block" form out of `boost::dynamic_bitset` is filling in the extra bits of our `uint32_t`  with zeros. Then on the other end we create the `boost::dynamic_bitset` from that set of 32 bits making it now 32 instead of 21.

We either need to implicitly know the finalizer set size (seems like we should know that) or pass along in the message how many of the provided bits are relevant (21 vs 32).

**Comment by greg7mdp** [comment]
Oh thanks, I get it now. `boost::dynamic_bitset` does know its size, which appears to be lost when serialized, right?

**Comment by heifner** [comment]
> Oh thanks, I get it now. `boost::dynamic_bitset` does know its size, which appears to be lost when serialized, right?

Correct.

**Comment by heifner** [comment]
Change `boost::dynamic_bitset` to use `uint8_t` to be less wasteful and to avoid zigzag encoding.
