### ISSUE TITLE
192 compile warnings in fc/secp256k1

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#19]
fc/secp256k1 has 192 compile warnings. They are in the form of

```
libraries/fc/secp256k1/secp256k1/src/field.h:44:13: warning: ‘secp256k1_fe_normalize’ declared ‘static’ but never defined [-Wunused-function]
libraries/fc/secp256k1/secp256k1/src/field.h:47:13: warning: ‘secp256k1_fe_normalize_weak’ declared ‘static’ but never defined [-Wunused-function]
...
libraries/fc/secp256k1/secp256k1/src/ecmult_impl.h:395:12: warning: ‘secp256k1_ecmult_strauss_batch_single’ defined but not used [-Wunused-function]
```

They should be cleaned up after the decision of de-submoduling is made.

**Comment by spoonincode** [comment]
I don't think we've considered desubmoduling this library since we use it verbatim without any modifications.

But the good thing is, we completely control compilation of this library since we use our own CMakeLists.txt (https://github.com/AntelopeIO/fc/blob/main/secp256k1/CMakeLists.txt), so it's trivial to add a `-Wnounused-function` option here and/or consider these SYSTEM headers.

**Comment by stephenpdeos** [comment]
Blocked by [Desubmodularize fc#122](https://github.com/AntelopeIO/leap/issues/122)
