### ISSUE TITLE
Remove broken `large-lib-test.py`

### ISSUE THREAD

**Issue by greg7mdp** [AntelopeIO/leap#2232]
After restarting the producer and `spec2` nodes, the producer doesn't start producing:

`Not Scheduling Speculative/Production, no local producers had valid wake up times`

and quickly syncs upon receiving blocks from `spec1`. The test seems to pass by chance.

Note: the test is broken in `main` as well, I means it passes but doesn't work as it is supposed to.

**Comment by arhag** [comment]
This test is intentionally causing a finality violation and relying on non-deterministic behavior that the new branch from genesis wins over the old one (which shouldn't necessarily be the case). We will have intentional tests for finality violation in IF (we do not need to bother adding one now for the pre-IF algorithm). So this test serves no purpose and should actually just be removed.
