### ISSUE TITLE
IF: Test Failure: nodeos_startup_catchup_if_lr_test

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#2351]
`AssertionError: Expected to at least receive 9.0 transactions per block, but only getting 7.6`

It is not clear what is going on here. Could just mean our ci/cd could not keep up. Or maybe all the voting is slowing it down enough it can't process trxs quick enough. Would be worth looking closer at the logs. Might need more net threads to allow trx processing along with vote processing. We should consider processing votes in its own thread pool so they can't clog the net thread pool. 

Happened at the same time: 
https://github.com/AntelopeIO/leap/actions/runs/8467659168/job/23199344820 ubsan
https://github.com/AntelopeIO/leap/actions/runs/8467659168/job/23199345763 ubnuntu22repo

**Comment by heifner** [comment]
Happened at the same time: 
https://github.com/AntelopeIO/leap/actions/runs/8467659168/job/23199344820
https://github.com/AntelopeIO/leap/actions/runs/8467659168/job/23199345763

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/8467659168/job/23202047049

**Comment by greg7mdp** [comment]
Issue was caused by the addition of two new tests in https://github.com/AntelopeIO/leap/pull/2335.

Two workflow runs with these tests removed passed without problems. https://github.com/AntelopeIO/leap/actions/runs/8523025337

#### Resolution:

@spoonincode will beef up the instances  the workflows are run on for: `NP`, `LR`, `ubsan`, `asan`, `asserton`
