### ISSUE TITLE
Design API call for various use cases for snapshots for blocks that haven't been produced yet

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/leap#396]
Scenario 1: Create a snapshot for a specific block num
Scenario 2: Create a snapshot every X number of blocks

Other considerations
- Ability to query existing requests and cancel them
- Do pending requests persist across nodeos restarts?

**Comment by kj4ezj** [comment]
We also discussed on video that these API calls should not block. For example, the current API call blocks until a snapshot has been taken. However, in these new scenarios, the API calls would be blocking for days or weeks, which is not normal.

**Comment by matthewdarwin** [comment]
The existing snapshot API also lets calls accumulate.  Run a snapshot while a previous one is running.  Both calls block. Then you get 2 snapshots, one after another. 

Should be able run /v1/get-snapshot-status (or similar) to understand what is happening.

**Comment by matthewdarwin** [comment]
I wonder how often snapshots will be produced and how long they will be kept for.

To allow users to get up to speed quickly you want a recent snapshot.
To avoid blowing up disk space you don't want them too often.

On snapshots.eosnation.io recent snapshots are every 3 hours.  Older snapshots are 2 per week.

Hopefully we can do something similar here.  (Using this algorithm, on WAX, snapshots take 1.8TiB space right now)

**Comment by aaroncox** [comment]
Scenario 2 would be very useful for anyone looking to run/setup our history solution (which is fed by the `trace_api` plugin). This feature would be something like `--snapshot-every-nth-block=10000000` as a configuration parameter, and when nodeos hits that interval (height of 10m, 20m, 30m, etc) either while syncing or replaying, it automatically outputs a named snapshot (file snapshot-10m, snapshot-20m, etc) at that specific height. 

This would dramatically speed up the setup of a new history API, since most of the time this process takes involves nodeos generating the `trace_api` output. I believe this would also assist with the dfuse/deepmind setup as well.

Currently the most simple, yet most time intensive way to generate all `trace_api` output is to use a single nodeos process starting from block 1 and let it sync to head. This on large chains could take weeks.

This however can be sped up by running multiple `trace_api` instances in parallel, each responsible for a different segment of the blockchain. As an example, imagine a chain with 250 million blocks, a server with 10 cores, running 10 nodeos instances w/ the `trace_api`, each nodeos instance responsible for a different segment of the blockchain.

1. nodeos starting at height 1 (no snapshot), with `--terminate-at-block 25,000,000`
2. nodeos starting at height 25,000,000 (using snapshot-25m), with `--terminate-at-block 50,000,000`
3. nodeos starting at height 50,000,000 (using snapshot-50m), with `--terminate-at-block 75,000,000`
4. etc etc, with 10 total nodes.

Each of these processes will process 25m blocks and output 25m blocks worth of `trace_api` output. When all these processes are complete, the output from all 10x of these processes can be moved into the same folder to form a complete data set representing the `trace_api` output. This example would see a ~10x reduction in the amount of time it takes to generate this data.

In the above example, note how it requires snapshots at specific heights. 

We recently ran into a situation where we were deploying a new Telos history API - and had to replay the `trace_api` from block 1 in a single thread to the head block. We didn't have the snapshots we needed in order to do a parallel replay like this, nor could we create those snapshots without investing time to manually generate them all. This is where this automatic snapshot creation feature would come into play, easily allowing snapshots at those set intervals to be created for use in parallelized configurations like this.
