### ISSUE TITLE
Gelf logging should use its own io_context

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#650]
Currently `gelf_appender` uses the main `application` `io_context`. This bypasses the application's priority queue and affectively means that gelf logging runs at the highest priority. This is clearly not what is intended. Gelf logging should be modified to use its own thread and its own `io_context`.

In my mind this should not wait for a new logging framework: https://github.com/eosnetworkfoundation/mandel/issues/152

**Comment by spoonincode** [comment]
A couple other things to consider while touching this code:

gelf_appender is using some fc wrappers over asio stuff (and the wrappers are fairly old style, such as usage of the deprecated io_service instead of io_service). This is generally something we're trying to move away from: just use boost directly. Consider refactoring accordingly and removing the wrappers.

A separate thread is, imo, not strictly required. There will be very little back pressure on a UDP socket so a large socket buff (say 1MB or 2MB) would be really surprising to fill up (at which point gelf_appender could just drop the message on the floor instead of `async`ing it). I'm certainly not saying it needs to be done this way, but imo it would be fine to simplify it further like this. Obviously other opinions welcome.

**Comment by heifner** [comment]
Probably more gain from moving the `format_string` and `zlib_compress` to another thread. But something in gelf logging takes a considerable amount of time: https://github.com/AntelopeIO/leap/issues/555

**Comment by spoonincode** [comment]
huh, yes that's really good point and almost certainly what ought to be attempted if this code is being touched.

**Comment by spoonincode** [comment]
resolved in #758
