### ISSUE TITLE
Add TestHarness python integration scripts to dev package

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#707]
It would be useful to have the python integration scripts `TestHarness/*` scripts in an installable package so integration tests could be created/run without having to build a complete Leap checkout.

Either include in the existing dev package or into a new `python3-leap-testharness` package.

**Comment by stephenpdeos** [comment]
Agreed to keep in existing dev package.

**Comment by heifner** [comment]
- Need to have the dev install use the dev installed: nodeos, cleos, eosio-launcher
- core_symbol.py - The def install will need a way to specify the CORE_SYMBOL instead of the default of SYS (the default leap is built with)
-

**Comment by spoonincode** [comment]
When we discussed this at one point a week or two ago, one aspect that came up was what to do with the system contracts that the python stuff requires.

For libtester, the system contracts are embedded in to the library. The reason I did it this way was because it makes it easy to ensure the contracts are always available and not fuss around with what path to use (which may be different depending on whether the library has been installed or packaged or such). I wonder for Python what the best strategy would be?
