### ISSUE TITLE
change on main's `abi_def`(?) causing native contract unit tests for system contracts to fail compile

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#741]
On main, there is some change in `abi_def` (or something closely related I didn't track it down) that is causing system contracts' native contract unit tests to fail to compile. See 
https://github.com/eosnetworkfoundation/eos-system-contracts/actions/runs/4248437173 for example. Also encountered it on EVM contract. I wouldn't be surprised if many native contract unit tests out in the wild would be ensnared by this.

Depending on the difficulty of getting this `abi_def` difference resolved, we could also just say it requires everyone downstream to update their test code. If that's the case, need to create issues in eos-system-contracts & reference-contracts.

**Comment by heifner** [comment]
This was caused by: https://github.com/AntelopeIO/leap/pull/696 Specifically the change https://github.com/AntelopeIO/leap/pull/696/commits/62903c04ab510784e255e4e38d67fd7cb5e27ba6
In the past when we changed `abi_serializer` we deprecated the methods when we realized it caused this kind of issue. Those methods are still there and deprecated actually. We could do the same thing for `set_abi` and a constructor that takes by `const&` instead of by rvalue reference.
