### ISSUE TITLE
Add configuration for 3-strike-rule time frame

### ISSUE THREAD

**Issue by huangminghuang** [AntelopeIO/leap#760]
Based on the conversion from https://github.com/AntelopeIO/leap/issues/315#issuecomment-1329968231

Add a new configuration to the existing 3-strike-rule
- Currently has configurable amount of strikes
  - `subjective-account-max-failures` - `Sets the maximum amount of failures that are allowed for a given account per block.` Defaults to 3.
  - Change this description to say `.. per subjective-account-max-failure-time-ms`
- Add new option
  - `subjective-account-max-failure-time-ms` - `Sets the time over which subjective-account-max-failures is enforced.` Defaults to 500ms.

**Comment by heifner** [comment]
Target change for 3.1, 3,2, & main.

**Comment by matthewdarwin** [comment]
So we would have the 3-strike-rule on a per block basis and a new rule for multiple blocks?  Can we have some names for these things so we can explain them?

**Comment by heifner** [comment]
The idea is to change the hard-coded block time to be configurable.

**Comment by matthewdarwin** [comment]
Ah, so not a different rule. So really it is adding a new configuration option, as was originally.  Title of this issue could probably be more clear.

**Comment by heifner** [comment]
Would time in milliseconds or number of blocks be better?

**Comment by DenisCarriere** [comment]
**Per block** seems like it would be a better fit

I'm assuming the milliseconds would need to match the block intervals (500ms), correct?

**Comment by heifner** [comment]
> **Per block** seems like it would be a better fit
> 
> I'm assuming the milliseconds would need to match the block intervals (500ms), correct?

No, it could be reset at any time. If time based you would just check the time at each failure (or start of trx).

**Comment by DenisCarriere** [comment]
Ahh.. well in that case i'll leave it to @matthewdarwin to provide a preference

I don't have any objections to either per block or per milliseconds

milliseconds would be the most flexible if it's not bound to block time intervals.

**Comment by matthewdarwin** [comment]
Time is more flexible.

**But** there is discussion about having block intervals change (depending on the fullness of the block and release it early).  When that that features is implemented, then I think you need this feature to be by block and not by time.  Unless that feature is magically moving the time forward and the counter that would reset the 3-strikes-rule automatically moves forward as well.

**Comment by heifner** [comment]
> **But** there is discussion about having block intervals change (depending on the fullness of the block and release it early). When that that features is implemented, then I think you need this feature to be by block and not by time. Unless that feature is magically moving the time forward and the counter that would reset the 3-strikes-rule automatically moves forward as well.

From this comment it does appear that you think about this in terms of blocks more than in terms of time.

**Comment by matthewdarwin** [comment]
If we're talking about "blocking" an account for a long period of time (say on the order of 1 minute) then shifting blocks around by a few ms doesn't matter one way or another. 

But since the configuration parameter is number of ms, then  it means we're thinking about blocking accounts for some small (on human scale) amount of times, less than 1 entire block production cycle (6 seconds).  If we are really trying to just prevent empty blocks and not punish the account, then we need to control to the block level (under the conditions that blocks are shifting around). You get banned for 2 or 3 blocks, for example. With ms counter the number of blocks you are banned for is not fixed.

Now I'm really not sure if banning for 2 blocks is enough to prevent the problem we are seeing in the wild right now.  Maybe it needs to be a longer ban period (like the entire rest of the 6 second block production cycle) to actually make a difference.  But that long a ban probably starts impacting regular users noticeably, which is what we want to avoid.

Under the current load can we quickly do a test what it takes to make the empty blocks go away?

In other thought, should the TRX_TRACE message print when you're banned until?

**Comment by heifner** [comment]
> In other thought, should the TRX_TRACE message print when you're banned until?

Seems reasonable.

**Comment by matthewdarwin** [comment]
Just to note, setting `subjective-account-max-failures = 1` has some positive impact on the situation, regardless of having this new setting.
