### ISSUE TITLE
Read-only transaction processing - Interrupt executing transactions at the end of the read window

### ISSUE THREAD

**Issue by greg7mdp** [AntelopeIO/leap#837]
Currently, when the timer marking the end of the read window is triggered, we wait for the readonly tasks to finish, so we don't strictly respect the requested window duration.

**Comment by heifner** [comment]
Also would like to interrupt read-only and normal trxs when a block arrives at the node.

**Comment by linh2931** [comment]
We don't have this issue. In `push_read_only_transaction`, we call `chain.push_transaction( trx, window_deadline, _ro_max_trx_time_us, 0, false, 0 );`, where `window_deadline` is  `std::min( start + remaining_time_in_read_window_us, block_deadline );`. A transaction will be interrupted if the window_deadline is reached, and the thread won't schedule any any transactions when this happens.

So when read window timer expires, all threads have finish execution. For safety, before switching to write window, we make sure all threads indeed finish executing. This is not the read-window duration is not respected.

**Comment by arhag** [comment]
> Also would like to interrupt read-only and normal trxs when a block arrives at the node.

@heifner: 
We discussed already privately, but I am summarizing here as well for others to make it clear we didn't miss the above quoted point when closing this issue either.


The summary is that we do not think it is worth the added complexity of interrupting any actively executing read-only transactions (or for that matter any other read-only tasks) when a new block is received. Already when a new block is received, it will end the read window after all read threads finish the task they are currently working on. 

In the case of read-only transactions that should not exceed max-transaction-time (or the time until the end of the read window whichever is sooner). In the case of other read operations, they are already expected to have their own sensible limits to protect against abuse (remember that prior to https://github.com/AntelopeIO/leap/pull/901 these read operations were running serially on the main application thread and so they were delaying other high priority operations that had just been queued and were waiting to run on the main application thread like processing a newly received block). So the transition from the read window to the write window may be delayed the maximum of one of these sensible limits.

Perhaps that delay would be unacceptable on a block producer node (or any of their canary nodes they depend on to receive blocks) because getting and processing blocks quickly is important to minimize microforks. But those types of nodes should not be running nodeos in a mode that has a read window anyway (the read window is really there for API nodes). In fact, nodeos prevents it from even being configured with producers and positive read threads at the same time.

For other types of nodes that have a reason to enable read threads, the slight delay this can add to processing the latest block (which again should be significantly less than 500 ms) is not that big of a deal and so we can avoid the extra complexity of trying to interrupt the read tasks upon receiving a new block.
