### ISSUE TITLE
`ship_test` struggles to complete in some environments

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#861]
`ship_test` seems to either never complete (for me, times out after 1500s limit), or, as reported by @linh2931
> The test is really slow. With my pinned build, the IP version test run successfully but in 1,416 seconds, now it is running the unix-socket version. It was stuck in "Wait for system init transaction to be in a block".

It doesn't have this problem in CI, so maybe something to do with the performance of the environment is causing it problems.

**Comment by heifner** [comment]
I recently increased the number of clients from 1 to 10 so that it tests with multiple clients. Maybe that is too aggressive for some environments. We could reduce that to 3 maybe.

However, the "Wait for system init transaction to be in a block" is before the test actually starts any of the clients, so that would seem to point to something else. This test should be no different than any other test up to that point. It is just launching the cluster and setting the system contract and calling init on it. Almost all the integration tests do exactly the same thing.

**Comment by linh2931** [comment]
Probably nothing to do with the number of clients. I noticed after that waiting was over, the test went through quickly. But as you pointed out, most tests do that waiting too.

**Comment by spoonincode** [comment]
The (consistent) failure I was seeing was on a 60+ core Sapphire Rapids CPU -- pretty much Intel's latest server CPU. So possibly it's a problem with fast environments, not slow environments. tbh I haven't tried in more environments to get a better feel for how common the failure is.

**Comment by linh2931** [comment]
It does seem to have something to do with the number of SHiP clients. equal to or less than 6 works in my machine.

**Comment by linh2931** [comment]
It is a regression from 3.2. The test itself in 3.2 only tests 1 client. I modified it for 10 clients; it works fine.
