### ISSUE TITLE
Configurable limit of unapplied_transactions per account/authorizer

### ISSUE THREAD

**Issue by cmadh** [AntelopeIO/leap#89]
Node-Operators on WAX recently saw issues in block-production related to heavily filled unapplied_transactions-queues.
 
While still unsure about the exact issues it furthermore looked like huge parts of the queue where filled with failing transactions leading into consumption of a huge amount of transaction-processing time without transactions beeing applied to the block produced.

Talking about the unapplied_transactions-queue we questioned if a configurable limit for unapplied_transactions per account in that queue would help in such scenarios a the lack of a per-account-limit basically allows a single account to push as many trx as possible filling up the queue. Even with subjective-billing enabled a single account would be able to fill up the queue with failing transactions.

Probably "subjective-account-max-failures" ( added in https://github.com/eosnetworkfoundation/mandel/releases/tag/v3.1.0-rc1) kicks in at some point but it's not clear how exactly it works.

An important question is probably what is a sustainable and reliable limit and how to distinguish between authorizers. A co-signing service could legitimately push hundreds of transactions per block and blocking such an account would be against the core design of the protocol and harm non-malicous users and services.

**Comment by cmadh** [comment]
There's additional clarity regarding "subjective-account-max-failures" needed.

"Account max failures: During block production, accounts are permitted a set number of failures before their additional transactions are dropped for a given block. This previously hard-coded limit of 3 is now configurable. Also, disable-subjective-account-billing accounts are no longer subjected to this limit."

Does that mean these trx are removed entirely from the queue or are they just moved to and processed in the next block potentially leading into the queue filling up even more?!

**Comment by heifner** [comment]
> Talking about the unapplied_transactions-queue we questioned if a configurable limit for unapplied_transactions per account in that queue would help in such scenarios a the lack of a per-account-limit basically allows a single account to push as many trx as possible filling up the queue. Even with subjective-billing enabled a single account would be able to fill up the queue with failing transactions.

A subjective limit on the number of trxs an authorizer is allowed in a block could certainly be added; and/or subjective limit on the number of trxs per contract.

> "subjective-account-max-failures" 

This option provides a configurable limit to the previous hard-coded limit of 3. When the first authorizer hits this configurable limit of failed transactions for a single block, during block production, all other trxs processed during that block are failed with a cpu usage exception. 

For example, say there are 100 trxs in the `unapplied_transaction_queue` for a given first authorizer. During the processing of the trxs in the unapplied transaction queue if 3 (or configured limit) fail, then all other trxs with that first authorizer will be immediately failed with a cpu usage exception.

-----------------------------------------------------------------------
unapplied_transaction_queue: 
[`trx1-auth-a, trx2-auth-b, trx3-auth-a, trx4-auth-a, trx5-auth-a, trx6-auth-c, trx7-auth-a`, `...`]
- `trx1-auth-a` - first transaction in the queue, its first authorizer is `a`. It runs successfully.
- `trx2-auth-b` - different first authorizer of `b` - it fails or succeeds, doesn't matter for this example
- `trx3-auth-a` - first authorizer `a` - it fails - that is 1 strike against first authorizer `a`
- `trx4-auth-a` - first authorizer `a` - it also fails - that is 2 strikes against first authorizer `a`
- `trx5-auth-a` - first authorizer `a` - it also fails - that is 3 strikes against first authorizer `a`
- `trx6-auth-c` - first authorizer `c` - it fails or succeeds, doesn't matter for this example
- `trx7-auth-a` - first authorizer `a` - this transaction is not executed it is marked as failed via a cpu usage exception
- `trx`[8-100]`-auth-a` - all the rest of the trxs in the queue that are first authorizer `a` are all failed via cpu usage exception. They might be perfectly valid transactions, but we will never know as they are immediately failed without evaluation.
If there is any block time left and a trx with first authorizer `a` comes in during the same block, it will also be failed with cpu usage exception.

This process is restarted for the next block. If there were other trxs in the `unapplied_transaction_queue` so that not all 100 of the first authorizer `a` were processed during the first block, then you get 3 more strikes in the new block before failing transactions of that first authorizer again.

Note any failed transactions have the possibility of being executed on a different block producer during their block production time.

-----------------------------------------------------------------------

> Does that mean these trx are removed entirely from the queue or are they just moved to and processed in the next block potentially leading into the queue filling up even more?!

Hopefully the description above helps (if not please ask follow on questions). Only those trxs reached in the unapplied_transaction_queue have the potential to be dropped.

- Block Production Time
  - Start block
    - Process `unapplied_transaction_queue`
  - If time remains, process trxs as they come into the node
  - Block production time reached, finalize block, sign it, and send it out P2P network

Sometimes the complete block production time is spent in the process `unapplied_transaction_queue` step without making it through the complete queue. In those cases only the trxs reached are dropped. In other words, the node does not scan forward in the unapplied_transaction_queue looking for the first authorizers, instead it just takes them as the are pulled off the queue.

**Comment by stephenpdeos** [comment]
Since this was mostly Q&A, closing for now, but feedback will be considered in design for future potential solutions like Contract Pays
